# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    packages:
      - awscli
      # Use Elixir from Erlang Solutions. The provided Elixir is
      # installed with kiex but is old. We also can't use kiex to
      # install a newer one because of GitHub API rate limiting.
      - elixir=1.6.0-1
cache:
  apt: true

otp_release:
  - "19.3"
  - "20.3"

install: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zip xsltproc

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We fetch master and, if it exists, v3.7.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.7.x:v3.7.x || :
    git fetch upstream master:master || :
  # Make sure we use Elixir from Erlang Solutions and not kiex.
  - |
    echo YES | kiex implode
    elixir --version
    elixir --version | grep -q 'Elixir 1.6.0'
  - |
  # Download ghr to upload compiled packages to github
    GHR_RELEASE='v0.10.0'
    curl -L -O https://github.com/tcnksm/ghr/releases/download/${GHR_RELEASE}/ghr_${GHR_RELEASE}_linux_amd64.zip
    unzip ghr_${GHR_RELEASE}_linux_amd64.zip
    rm ghr_${GHR_RELEASE}_linux_amd64.zip
    mv ghr /usr/local/bin
script:
  - make tests
  - make dist

